In [11]:
from sklearn.model_selection import train_test_split
from datasets import Dataset, DatasetDict
import numpy as np
import pandas as pd
import os
from PIL import Image, ImageColor
import os
from tqdm import tqdm

# 태그 라벨

In [12]:
import os

def list_folders_in_directory(path):
    folder_list = []
    
    # 경로 내의 모든 항목을 가져옵니다.
    items = os.listdir(path)
    
    # 각 항목에 대해 폴더인지 확인하고 리스트에 추가합니다.
    for item in items:
        item_path = os.path.join(path, item)
        if os.path.isdir(item_path):
            folder_list.append(item)
    
    return folder_list

# 경로 지정
directory_path = '/mnt/c/Users/user/DATA/image_to_tag/train_imgs_result'

# 폴더 리스트 얻기
folders = list_folders_in_directory(directory_path)

folders

['advertising',
 'ambiental',
 'calm',
 'christmas',
 'cool',
 'dark',
 'dream',
 'energetic',
 'game',
 'groovy',
 'happy',
 'horror',
 'love',
 'movie',
 'retro',
 'sad',
 'space',
 'sport']

In [13]:
# 리스트를 DataFrame으로 변환
tag_list = pd.DataFrame(folders, columns=['label_name'])
tag_list

     label_name
0   advertising
1     ambiental
2          calm
3     christmas
4          cool
5          dark
6         dream
7     energetic
8          game
9        groovy
10        happy
11       horror
12         love
13        movie
14        retro
15          sad
16        space
17        sport

In [14]:
tag_list['label'] = range(0, len(tag_list) )
tag_list

     label_name  label
0   advertising      0
1     ambiental      1
2          calm      2
3     christmas      3
4          cool      4
5          dark      5
6         dream      6
7     energetic      7
8          game      8
9        groovy      9
10        happy     10
11       horror     11
12         love     12
13        movie     13
14        retro     14
15          sad     15
16        space     16
17        sport     17

In [15]:
# tag_list.to_csv('/mnt/c/Users/user/image_to_tag/label_data/tag_result_list.csv', index=False, encoding='utf-8')

In [16]:
#### tag list ####

folder_list =[]
def get_folder_names(directory):
    folder_names = []
    for entry in os.scandir(directory):
        if entry.is_dir():
            folder_names.append(entry.name)
    return folder_names

# 폴더명을 불러올 디렉토리 경로를 지정합니다.
directory_path = '/mnt/c/Users/user/DATA/image_to_tag/train_imgs_result'

# 폴더명을 불러옵니다.
folders = get_folder_names(directory_path)

# 폴더명을 출력합니다.
for folder in folders:
    folder_list.append(folder)
folder_list

['advertising',
 'ambiental',
 'calm',
 'christmas',
 'cool',
 'dark',
 'dream',
 'energetic',
 'game',
 'groovy',
 'happy',
 'horror',
 'love',
 'movie',
 'retro',
 'sad',
 'space',
 'sport']

In [17]:
import os

# 폴더 
def get_folder_names(directory):
    folder_names = []
    for entry in os.scandir(directory):
        if entry.is_dir():
            folder_names.append(entry.name)
    return folder_names

def get_jpg_files_in_folder(folder_path):
    jpg_file_list = []
    for root, _, files in os.walk(folder_path):
        for file in files:
            if file.lower().endswith('.jpg'):  # 파일 확장자가 .jpg 인 경우만 추가
                file_path = root + '/' + file
                jpg_file_list.append(file_path)
    return jpg_file_list

In [18]:
columns = ['dir', 'label_name', 'image'] 
tag_image = pd.DataFrame(columns=columns)

In [19]:
num=0
for folder in tqdm(folder_list):
  # 폴더안의 jpg 불러오기
  directory_path = f'/mnt/c/Users/user/DATA/image_to_tag/train_imgs_result/{folder}'
  jpgs = get_jpg_files_in_folder(directory_path)

  # jpg 
  for jpg in jpgs:
    with Image.open(jpg) as img: # Too many open files 오류 해결

      tag_image.loc[num, 'dir'] = jpg
      tag_image.loc[num, 'label_name'] = folder
      tag_image.loc[num, 'image'] = img

    num+=1
    
tag_image

100%|███████████████████████████████████████████████████████████████████████████████████| 18/18 [00:25<00:00,  1.44s/it]

,dir,label_name,image
0,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...
1,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...
2,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...
3,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...
4,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...
...,...,...,...
7523,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...
7524,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...
7525,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...
7526,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...
7527,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...

In [20]:
dataset = tag_image.merge(tag_list, on='label_name', how='left')
dataset

,dir,label_name,image,label
0,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...,0
1,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...,0
2,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...,0
3,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...,0
4,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,advertising,<PIL.JpegImagePlugin.JpegImageFile image mode=...,0
...,...,...,...,...
7523,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...,17
7524,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...,17
7525,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...,17
7526,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...,17
7527,/mnt/c/Users/user/DATA/image_to_tag/train_imgs...,sport,<PIL.JpegImagePlugin.JpegImageFile image mode=...,17

In [21]:
dataset.drop(columns='image',inplace=True)
dataset

                                                    dir   label_name  label
0     /mnt/c/Users/user/DATA/image_to_tag/train_imgs...  advertising      0
1     /mnt/c/Users/user/DATA/image_to_tag/train_imgs...  advertising      0
2     /mnt/c/Users/user/DATA/image_to_tag/train_imgs...  advertising      0
3     /mnt/c/Users/user/DATA/image_to_tag/train_imgs...  advertising      0
4     /mnt/c/Users/user/DATA/image_to_tag/train_imgs...  advertising      0
...                                                 ...          ...    ...
7523  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...        sport     17
7524  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...        sport     17
7525  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...        sport     17
7526  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...        sport     17
7527  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...        sport     17

[7528 rows x 3 columns]

In [22]:
# dataset.to_csv('/mnt/c/Users/user/DATA/image_to_tag/tag_dir_label.csv', index=False, encoding='utf-8')

In [23]:
# dataset = pd.read_csv('/mnt/c/Users/user/image_to_tag/image_to_tag/data/tag_dir_label.csv')
# dataset

In [24]:
train_df, test_df = train_test_split(dataset, test_size=0.2, random_state=42)
train_df

                                                    dir label_name  label
5229  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...     horror     11
2087  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...       dark      5
6746  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...      space     16
4110  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...     groovy      9
7204  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...      sport     17
...                                                 ...        ...    ...
5191  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...     horror     11
5226  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...     horror     11
5390  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...     horror     11
860   /mnt/c/Users/user/DATA/image_to_tag/train_imgs...       calm      2
7270  /mnt/c/Users/user/DATA/image_to_tag/train_imgs...      sport     17

[6022 rows x 3 columns]

In [25]:
train_df = train_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

In [26]:
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

In [27]:
train_dataset['label'][0]

11

In [28]:
train_dataset

Dataset({
    features: ['dir', 'label_name', 'label'],
    num_rows: 6022
})

In [29]:
data_image = DatasetDict({
    "train": train_dataset,
    "test": test_dataset
})

data_image

DatasetDict({
    train: Dataset({
        features: ['dir', 'label_name', 'label'],
        num_rows: 6022
    })
    test: Dataset({
        features: ['dir', 'label_name', 'label'],
        num_rows: 1506
    })
})

In [30]:
data_image.save_to_disk("/mnt/c/Users/user/DATA/image_to_tag/train_imgs_datasets")

Saving the dataset (0/1 shards):   0%|          | 0/6022 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1506 [00:00<?, ? examples/s]